### ISSUE TITLE
Live verification during RPM package and `make check` fails

### ISSUE THREAD

**Issue by mwinter-osr** [rtrlib/rtrlib#274] opened 2022-04-25 09:29 UTC
### Live verification during RPM package and `make check` fails

The live verification checks during the `make check` and during the RPM package build (in the test phase) are failing as the RPKI server used seems to be longer available (or offline for days/weeks)

```
Start 1: test_pfx
1/9 Test #1: test_pfx .........................   Passed    0.59 sec
Start 2: test_trie
2/9 Test #2: test_trie ........................   Passed    0.00 sec
Start 3: test_ht_spkitable
3/9 Test #3: test_ht_spkitable ................   Passed    1.23 sec
Start 4: test_ht_spkitable_locks
4/9 Test #4: test_ht_spkitable_locks ..........   Passed    0.82 sec
Start 5: test_live_validation
5/9 Test #5: test_live_validation .............***Failed    1.00 sec
Start 6: test_ipaddr
6/9 Test #6: test_ipaddr ......................   Passed    0.00 sec
Start 7: test_getbits
7/9 Test #7: test_getbits .....................   Passed    0.00 sec
Start 8: test_dynamic_groups
8/9 Test #8: test_dynamic_groups ..............***Failed    1.00 sec
Start 9: test_bgpsec
9/9 Test #9: test_bgpsec ......................   Passed    0.01 sec
```

Both Test 5 and Test 8 use `rpki-validator.realmv6.org` as the RPKI server which is offline.

As a result, the RPM package build fails (and the `make check`)

**Comment by mroethke** [comment] 2022-04-25 16:10
The server running the rtr server is currently down.
I will see if I can point the domain to another rtr server in the short term.
In the long term we should probably just make it possible to use a local rtr server.

**Comment by mroethke** [comment] 2022-04-28 09:09
Should work again now, but there might be some intermittent reachability problems in in the next few days because the server needs to be taken down for maintenance again.

I will close this issue when the problem is fully resolved.

**Closed** 2022-05-02 18:44 UTC

**Comment by drewbowering** [comment] 2023-10-30 16:58
Hi,
I've been experiencing this issue for the past week. Is this live service down again?

**Comment by mroethke** [comment] 2023-10-31 19:08
yes it was, but it is fixed again. Thanks for pointing it out!

**Comment by drewbowering** [comment] 2023-10-31 19:14
> yes it was, but it is fixed again. Thanks for pointing it out!

Confirmed! Thank you!
