### ISSUE TITLE
Test RTRlib packages provided by FRR

### ISSUE THREAD

**Issue by waehlisch** [rtrlib/rtrlib#161] opened 2018-03-20 11:38 UTC
@mwinter-osr was asking that we test (install) the RTRlib packages that are provided by FRR?
https://ci1.netdef.org/browse/FRR-RPKI0-2/artifact

- [x] Ubuntu 16.04 ARM7
- [x]  Ubuntu 16.04 ARM8
- [x]  Ubuntu 14.04 x86_64
- [x]  CentOS 7 x86_64 
- [x]  CentOS 6 x86_64
- [x]  Debian 8 (Jessie) x86_64
- [x]  Ubuntu 16.04 x86_64
- [x]  Fedora 24 x86_64
- [x]  Debian 9 (Stretch) x86_64

**Comment by mwinter-osr** [comment] 2018-03-20 14:39
Best to take the packages from https://ci1.netdef.org/browse/FRR-RPKI0/latestSuccessful/artifact (which are the last build). I'm rebuilding them every time frr 4.0 is updated.

The matching RTRLIB packages are at https://ci1.netdef.org/browse/RPKI-RTRLIB/latestSuccessful/artifact (rebuilt from this git everytime master branch changes)

These are based on FRR 4.0 which just got released. The currently published FRR 4.0 packages do not have the RPKI enabled (They could be recompiled with the option enabled) and I was planning to publish RPKI packages additionally to the non-RPKI packages. I just need someone to give me some feedback if they work.

I don't need them all tested. Minimum would be one of these packages verified, but preferably one RPM based and one debian based package.

On the longer term, I'm planning to add automated tests but prefer to do this in a simulated offline version (= not connecting to public validators, but using some fake validator) if this is somehow feasible (as discussed with @waehlisch)

**Comment by mroethke** [comment] 2018-05-14 16:08
I was unable to start frr with rpki enabled on centos6, it seems the module is missing. I believe other rpm distros are also affected.

Regarding automated testing:
The upcoming rpki-validator 3 decouples the cache from the rtr server implementation. The rtr server gets the data via http in json format and and it is possible to run the rtr server without the cache. One could either dump the json file or handcraft one and serve it to the rtr server locally, that way no network access would be required.

**Comment by mwinter-osr** [comment] 2018-05-14 20:31
Can you tell me if you got any error messages and which ones?
And which module do you expect missing?

(We are in the phase to close down on FRR 5.0, so would love to get RPKI fixed)

**Comment by mroethke** [comment] 2018-05-15 11:08
The error message on centos6 is
`bgpd loading module "rpki" failed: rpki: cannot open shared object file: No such file or directory`

The file `bgpd_rpki.so` is indeed missing in the file system and not present in the rpms. It is in the debs though.

**Comment by mwinter-osr** [comment] 2018-05-15 11:37
Thanks for the update.
So it sounds like the RPMs are broken (CentOS 6,7, Fedora). I'll take care of this.
FRR Issue opened: https://github.com/FRRouting/frr/issues/2234

Any results on debian packages? You mentioned that the libs are present there, but do they work as intended?

**Comment by mroethke** [comment] 2018-05-15 12:12
I tested debian 9 and ubuntu 16.04, they connect to an rpki server without issues.
I will test the remainder of the deb files on Thursday, assuming running ubuntu arm in qemu runs without major issues.

**Comment by mroethke** [comment] 2018-06-01 08:01
Are the builds from yesterday supposed to be fixed? Because it seems they are still missing the module.

**Comment by mwinter-osr** [comment] 2018-06-02 00:55
Ouch.. Another bug in my CI system. Issue was fixed, but because of another typo in the CI system still built without RPKI support.

It's fixed now and new images for 4.0, 5.0 beta and master are available. I think this time it should be working...

Thanks for the feedback

**Comment by mroethke** [comment] 2018-06-04 08:49
I can confirm that the build for rpm based distros are working now.

**Closed by mroethke** 2018-06-04 08:49 UTC
Labels: priority:medium
